<?php
/**
 * xjoomla background

Requirements:
The database of xjoomla must bee seted in settings.php as 

$databases['xjoomla']['default'] = array(
    'database' => 'joomla_database',
    'username' => 'drupal',
    'password' => 'p',
    'host' => 'localhost',
    'port' => '',
    'driver' => 'mysql',
    'prefix' => '',
  );

// Connect to xjoomla database
$connection = Database::getConnection('default', 'xjoomla');
  $connectionOptions = $connection->getConnectionOptions();
  if($connectionOptions['database'] != 'joomla_database'){
    print '<div>Wrong database connection: ' . $connectionOptions['database'] . '<br /><strong>STOPPING</strong></div>';
    print '<div><a id="refresh" href="?set=' . ($set) . '&t=' . time() . '">Try again.</a></div>';
    exit(0);
  }

  // retrieve content from joomla system 
  $total_count = $connection->query("SELECT COUNT(id) FROM tourisnews_content n")->fetchField();
  $resultset = $connection->query("SELECT n.title, n.id, n.introtext, n.created, n.created_by FROM tourisnews_content n  WHERE 1 ORDER BY n.id ASC");
  foreach ($resultset as $result) {
    // do something
  }
  //make certain we switch back to the Drupal 7 database
  $connection = Database::getConnection('default', 'default');
  //do more stuff

 */

/**
 * Implementation of hook_menu().
function migrate_menu() {
  $items = array();

  $items['admin/content/migrate'] = array(
    'title' => 'Migrate',
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'description' => 'Monitor the creation of Drupal content from source data',
    'page callback' => 'migrate_ui_dashboard',
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );
  $items['admin/content/migrate/dashboard'] = array(
    'title' => 'Migrate',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/content/migrate/configure'] = array(
    'title' => 'Configure',
    'type' => MENU_LOCAL_TASK,
    'description' => 'Configure migration handlers',
    'page callback' => 'migrate_ui_configure',
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
    'weight' => 10,
  );
  $items['admin/content/migrate/messages/%migration'] = array(
    'title callback' => 'migration_title',
    'title arguments' => array(4),
    'description' => 'View messages from a migration',
    'page callback' => 'migrate_ui_messages',
    'page arguments' => array(4),
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );
  $items['admin/content/migrate/%migration'] = array(
    'title callback' => 'migration_title',
    'title arguments' => array(3),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('migrate_migration_info', 3),
    'access arguments' => array(MIGRATE_ACCESS_BASIC),
    'file' => 'migrate_ui/migrate_ui.pages.inc',
  );

  if (FALSE) {
    // Not working yet
    migrate_ui_menu_add($items);
  }

  return $items;
}
 */

?>
